### PR TITLE
some suggested changes

### PR DESCRIPTION
**Pull request by greglandrum**
Some suggested changes to make the code more consistent with the rest of the RDKit and to speed up the implementation a bit.

### CODE REVIEW

**Comment by apahl** [comment]
Thank you for looking into this. Really good proposals.  
I have compared your implementation as well as our's from the Hackathon against the original one by @frog2000 on a random subset of 250,000 compounds from ChEMBL.
All three versions give the same results when run with the same RDKit version (2023.09.1pre), so I would say that we are good to go.
However, one thing to note: the results of the implementations differ for 2 of the 250k compounds when run on different versions of the RDKit. The difference is 27 SPS units for both compound, the two structures are very similar:

| ChEMBL_Id | Smiles | SPS (RDKit 2023.03.1) | nSPS (RDKit 2023.03.1) | SPS (RDKit 2023.09.1pre) | nSPS (RDKit 2023.09.1pre) | delta_SPS |
| --- | --- | --- | --- | --- | --- | --- |
| CHEMBL1361685 | CCc1ccc(C(c2c(C)[nH]n(-c3ccccc3)c2=N)c2c(C)[nH]n(-c3ccccc3)c2=N)cc1 | 396 | 11.314286 | 423 | 12.085714 | 27 |
| CHEMBL1531820 | Cc1[nH]n(-c2ccccc2)c(=N)c1C(c1ccc(C(C)C)cc1)c1c(C)[nH]n(-c2ccccc2)c1=N | 414 | 11.500000 | 441 | 12.250000 | 27 |

I don't know, if this is worth investigating further.

KR Axel

**Comment by apahl** [comment]
So I looked into the deviation and it looks like v2023.09.1pre considers atom idx 6 ( no. 7 in this 1-based depiction) to be an undefined stereo atom, leading to a stereo term of `2`  for the atom in the SPS, whereas RDKit v2023.03.1 considers the atom to be achiral, resulting to an SPS atom score of `1`.  
Since the molecule is symmetric, I would consider the result of v2023.03.1 to be correct.

image

```
RDKit v2023.09.1pre:
>>> Chem.FindMolChiralCenters(mol, includeUnassigned=True, includeCIP=False, useLegacyImplementation=False)
[(6, '?')]

RDKit v2023.03.1:
>>> Chem.FindMolChiralCenters(mol, includeUnassigned=True, includeCIP=False, useLegacyImplementation=False)
[]
```

**Comment by apahl** [comment]
@greglandrum Should I create an issue for this?

**Comment by greglandrum** [comment]
yes please

**Pull request merged**
